version: "3.9"

services:
  poke-scraper:
    build: .
    container_name: poke_scraper
    working_dir: /app
    volumes:
      - ./src:/app/src          # bind mount for source code
      - ./data:/app/data        # bind mount for CSV output
    command: python ./src/pokemon_scraper.py